runtime: custom
env: flex
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10